### ISSUE TITLE
Create additional crawlers for sample datafiniti PLDs

### ISSUE THREAD

**Issue by Steffen911** [Steffen911/Master-Thesis#2]
**What**:
The following PLDs are not covered by crawlers yet:
- [x] asus.com 
- [x] abt.com 
- [x] officedepot.com 
- [x] Lazada.sg 
- [x] kmart.com 
- [x] overstock.com 
- [x] buy.com 
- [x] kohls.com 
- [x] lg.com 

**ToDo**:

- [x] Check number of products per PLD
- [x] Fetch category for most promising PLDs
- [x] Integrate into python script and run only for covered products
